import AppKit
import SwiftUI
import UniformTypeIdentifiers

@MainActor
struct AITokenRestoreSheet: View {
    @ObservedObject private var tokenService = AITokenSwapService.shared
    @Environment(\.dismiss) private var dismiss

    @State private var selectedSessionID: String = ""
    @State private var aiInputText: String = ""
    @State private var restoredText: String = ""
    @State private var replacementsCount: Int = 0
    @State private var isCopied = false
    @State private var statusMessage: String?

    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            // Header
            HStack(alignment: .top) {
                VStack(alignment: .leading, spacing: 3) {
                    HStack(spacing: 8) {
                        Image(systemName: "sparkles.rectangle.stack.fill")
                            .foregroundStyle(Color.palMint)
                        Text("AI Privacy Bridge — Restore Genuine Data")
                            .font(.system(size: 16, weight: .bold, design: .rounded))
                    }
                    Text("Paste the response generated by ChatGPT, Claude, or any AI model. Storage Pal will automatically swap real confidential values back into place.")
                        .font(.system(size: 12))
                        .foregroundStyle(Color.palMuted)
                }
                Spacer()
                Button {
                    dismiss()
                } label: {
                    Image(systemName: "xmark.circle.fill")
                        .font(.system(size: 18))
                        .foregroundStyle(.secondary)
                }
                .buttonStyle(.plain)
            }

            Divider()

            if tokenService.activeSessions.isEmpty {
                emptySessionsView
            } else {
                mainRestoreView
            }
        }
        .padding(24)
        .frame(minWidth: 700, minHeight: 520)
        .background(Color.palCream)
        .onAppear {
            if let first = tokenService.activeSessions.first {
                selectedSessionID = first.id
            }
        }
    }

    private var emptySessionsView: some View {
        VStack(spacing: 16) {
            Spacer()
            Image(systemName: "lock.slash.fill")
                .font(.system(size: 36))
                .foregroundStyle(Color.palMuted)
            Text("No Active AI Token Sessions Found")
                .font(.system(size: 15, weight: .bold))
            Text("First, pseudonymize a document in the Redaction Studio using 'AI Token Swap'. A local session mapping key will be created here.")
                .font(.system(size: 12))
                .foregroundStyle(Color.palMuted)
                .multilineTextAlignment(.center)
                .frame(maxWidth: 420)
            Spacer()
        }
        .frame(maxWidth: .infinity)
    }

    private var mainRestoreView: some View {
        VStack(alignment: .leading, spacing: 14) {
            // Session Selector
            HStack(spacing: 12) {
                Text("Active Token Session:")
                    .font(.system(size: 12, weight: .semibold))

                Picker("", selection: $selectedSessionID) {
                    ForEach(tokenService.activeSessions) { session in
                        Text("\(session.documentName) (\(session.tokenMap.count) tokens • \(session.template))")
                            .tag(session.id)
                    }
                }
                .labelsHidden()
                .frame(maxWidth: 380)

                Spacer()

                if let session = currentSession {
                    Button(role: .destructive) {
                        tokenService.deleteSession(id: session.id)
                        if let first = tokenService.activeSessions.first {
                            selectedSessionID = first.id
                        }
                    } label: {
                        Image(systemName: "trash")
                            .foregroundStyle(.red)
                    }
                    .buttonStyle(.plain)
                }
            }

            // Session mapping pills
            if let session = currentSession {
                sessionTokensBar(session: session)
            }

            // Split View: AI Input -> Restored Output
            HStack(spacing: 14) {
                // Left: AI Input
                VStack(alignment: .leading, spacing: 6) {
                    Text("PASTE AI OUTPUT HERE")
                        .font(.system(size: 10, weight: .bold))
                        .tracking(1)
                        .foregroundStyle(Color.palMuted)

                    TextEditor(text: $aiInputText)
                        .font(.system(size: 12, design: .monospaced))
                        .padding(8)
                        .background(Color.white.opacity(0.8), in: RoundedRectangle(cornerRadius: 8))
                        .overlay(
                            RoundedRectangle(cornerRadius: 8)
                                .strokeBorder(Color.palCardBorder, lineWidth: 1)
                        )
                        .onChange(of: aiInputText) {
                            performRestore()
                        }
                }

                // Right: Restored Output
                VStack(alignment: .leading, spacing: 6) {
                    HStack {
                        Text("REAL DATA RESTORED")
                            .font(.system(size: 10, weight: .bold))
                            .tracking(1)
                            .foregroundStyle(Color.palMint)
                        Spacer()
                        if replacementsCount > 0 {
                            Text("\(replacementsCount) token(s) restored")
                                .font(.system(size: 10, weight: .bold))
                                .foregroundStyle(Color.palMint)
                                .padding(.horizontal, 6)
                                .padding(.vertical, 2)
                                .background(Color.palMint.opacity(0.12), in: Capsule())
                        }
                    }

                    TextEditor(text: .constant(restoredText))
                        .font(.system(size: 12, design: .monospaced))
                        .padding(8)
                        .background(Color.white.opacity(0.8), in: RoundedRectangle(cornerRadius: 8))
                        .overlay(
                            RoundedRectangle(cornerRadius: 8)
                                .strokeBorder(Color.palMint.opacity(0.5), lineWidth: 1)
                        )
                }
            }
            .frame(height: 230)

            // Footer Actions
            HStack {
                if let msg = statusMessage {
                    Text(msg)
                        .font(.system(size: 12))
                        .foregroundStyle(Color.palMint)
                }

                Spacer()

                Button {
                    NSPasteboard.general.clearContents()
                    NSPasteboard.general.setString(restoredText, forType: .string)
                    isCopied = true
                    statusMessage = "Copied de-anonymized text to clipboard!"
                } label: {
                    Label(isCopied ? "Copied!" : "Copy Restored Text", systemImage: isCopied ? "checkmark" : "doc.on.doc")
                }
                .buttonStyle(PalButtonStyle(prominent: true))
                .disabled(restoredText.isEmpty)

                Button("Export Restored Document…") {
                    exportRestoredDocument()
                }
                .buttonStyle(PalButtonStyle())
                .disabled(restoredText.isEmpty)
            }
        }
    }

    private func sessionTokensBar(session: TokenSwapSession) -> some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 6) {
                ForEach(Array(session.tokenMap.keys.sorted()), id: \.self) { token in
                    if let realVal = session.tokenMap[token] {
                        HStack(spacing: 4) {
                            Text(token)
                                .font(.system(size: 10, weight: .bold))
                                .foregroundStyle(Color.palMint)
                            Image(systemName: "arrow.right")
                                .font(.system(size: 8))
                                .foregroundStyle(.secondary)
                            Text(realVal)
                                .font(.system(size: 10))
                                .foregroundStyle(Color.palInk)
                        }
                        .padding(.horizontal, 8)
                        .padding(.vertical, 4)
                        .background(Color.palMint.opacity(0.1), in: RoundedRectangle(cornerRadius: 6))
                    }
                }
            }
        }
    }

    private var currentSession: TokenSwapSession? {
        tokenService.activeSessions.first { $0.id == selectedSessionID }
    }

    private func performRestore() {
        guard let session = currentSession else { return }
        let (result, count) = tokenService.restoreRealData(aiResponseText: aiInputText, session: session)
        self.restoredText = result
        self.replacementsCount = count
        self.isCopied = false
    }

    private func exportRestoredDocument() {
        let panel = NSSavePanel()
        panel.nameFieldStringValue = "Restored_\(currentSession?.documentName ?? "Document").txt"
        panel.prompt = "Save Restored File"
        if panel.runModal() == .OK, let url = panel.url {
            try? restoredText.write(to: url, atomically: true, encoding: .utf8)
            statusMessage = "Saved to \(url.lastPathComponent)."
        }
    }
}
